on:
  push: {}
  workflow_dispatch: {}
  workflow_call: {}
  workflow_run: {}

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check Out
      - uses: actions/setup-java@v3
        name: Java Setup
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - run: ./mvnw --batch-mode --update-snapshots verify
        name: Runs Tests
